# Images Docker
images:
  repoAccount: "pueblo2708"
  pullPolicy: IfNotPresent
  tags:
    backend: "latest"
    frontend: "latest"
    cleaner: "latest"

# Backend (API Flask)
backend:
  replicas: 2
  logLevel: "INFO"
  service:
    type: ClusterIP
    port: 5000
  resources: {}

# Frontend (Nginx)
frontend:
  replicas: 1
  service:
    type: LoadBalancer
    port: 80
  resources: {}

# Redis — gere par le sous-chart bitnami/redis
redis:
  enabled: true
  auth:
    enabled: true
    password: "supersecret"
  master:
    persistence:
      storageClass: "standard-rwo"
      size: "1Gi"
  replica:
    replicaCount: 0
  architecture: standalone

# Cleaner (CronJob)
cleaner:
  schedule: "*/2 * * * *"
  maxAgeSeconds: 3600
