apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-cleaner
  labels:
    app.kubernetes.io/name: cleaner
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  schedule: {{ .Values.cleaner.schedule | quote }}
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: cleaner
              image: "{{ .Values.images.repoAccount }}/devops-news-cleaner:{{ .Values.images.tags.cleaner }}"
              imagePullPolicy: {{ .Values.images.pullPolicy }}
              env:
                - name: REDIS_HOST
                  value: "{{ .Release.Name }}-redis"
                - name: REDIS_PORT
                  value: {{ .Values.redis.service.port | quote }}
                - name: REDIS_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Release.Name }}-redis-secret
                      key: password
                - name: MAX_AGE_SECONDS
                  value: {{ .Values.cleaner.maxAgeSeconds | quote }}
